// <auto-generated />
using System;
using HorseRace.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HorseRace.DAL.Migrations
{
    [DbContext(typeof(HorseRaceDbContext))]
    [Migration("20260522102125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HorseRace.DAL.Entities.Entry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("HorseId")
                        .HasColumnType("integer");

                    b.Property<int>("HorseOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("JockeyId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntryId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("HorseId");

                    b.HasIndex("HorseOwnerId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId", "GateNumber")
                        .IsUnique()
                        .HasFilter("\"GateNumber\" IS NOT NULL");

                    b.HasIndex("RaceId", "HorseId")
                        .IsUnique();

                    b.HasIndex("RaceId", "JockeyId")
                        .IsUnique();

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Horse", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HorseId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("Breed")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HorseId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("OwnerId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.JockeyInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvitationId"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorseId")
                        .HasColumnType("integer");

                    b.Property<int>("HorseOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("JockeyId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvitationId");

                    b.HasIndex("HorseId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId");

                    b.HasIndex("HorseOwnerId", "JockeyId", "HorseId", "RaceId")
                        .IsUnique();

                    b.ToTable("JockeyInvitations");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Leg", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<string>("AdminOverrideReason")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmationType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConflictReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RaceId", "LegNumber");

                    b.ToTable("Legs", t =>
                        {
                            t.HasCheckConstraint("CK_Legs_LegNumber", "\"LegNumber\" >= 1 AND \"LegNumber\" <= 10");
                        });
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.LegOfficialResult", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfirmationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfirmedByAdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("integer");

                    b.Property<int>("LegPoints")
                        .HasColumnType("integer");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RaceId", "LegNumber", "EntryId");

                    b.HasIndex("EntryId");

                    b.ToTable("LegOfficialResults");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.LegRefereeEntry", b =>
                {
                    b.Property<long>("LegRefereeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LegRefereeEntryId"));

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("integer");

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("RefereeUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LegRefereeEntryId");

                    b.HasIndex("EntryId");

                    b.HasIndex("RefereeUserId");

                    b.HasIndex("RaceId", "LegNumber", "EntryId", "RefereeUserId")
                        .IsUnique();

                    b.ToTable("LegRefereeEntries");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.PasswordResetOtp", b =>
                {
                    b.Property<long>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OtpId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetOtps");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.PointWallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletId"));

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PointWallets", t =>
                        {
                            t.HasCheckConstraint("CK_PointWallets_Balance", "\"Balance\" >= 0");
                        });
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Prediction", b =>
                {
                    b.Property<long>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PredictionId"));

                    b.Property<int>("BetAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CorrectMatches")
                        .HasColumnType("integer");

                    b.Property<int>("FirstEntryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OddsLocked1")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OddsLocked2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OddsLocked3")
                        .HasColumnType("numeric");

                    b.Property<int?>("Payout")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("SecondEntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ThirdEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PredictionId");

                    b.HasIndex("FirstEntryId");

                    b.HasIndex("SecondEntryId");

                    b.HasIndex("ThirdEntryId");

                    b.HasIndex("UserId");

                    b.HasIndex("RaceId", "UserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.ToTable("Predictions", t =>
                        {
                            t.HasCheckConstraint("CK_Predictions_BetAmount", "\"BetAmount\" >= 1");
                        });
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxHorses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfLegs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OddsComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Referee1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Referee2Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RegistrationCloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RegistrationOpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RaceId");

                    b.HasIndex("Referee1Id");

                    b.HasIndex("Referee2Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Races", t =>
                        {
                            t.HasCheckConstraint("CK_Races_DifferentReferees", "\"Referee1Id\" <> \"Referee2Id\"");

                            t.HasCheckConstraint("CK_Races_NumberOfLegs", "\"NumberOfLegs\" >= 1 AND \"NumberOfLegs\" <= 10");
                        });
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.RaceResult", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinalPosition")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRaceDQ")
                        .HasColumnType("boolean");

                    b.Property<int>("LegTop3Count")
                        .HasColumnType("integer");

                    b.Property<int>("LegWinCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RaceId", "EntryId");

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Code = "HORSE_OWNER",
                            Name = "Horse Owner"
                        },
                        new
                        {
                            RoleId = 2,
                            Code = "JOCKEY",
                            Name = "Jockey"
                        },
                        new
                        {
                            RoleId = 3,
                            Code = "REFEREE",
                            Name = "Race Referee"
                        },
                        new
                        {
                            RoleId = 4,
                            Code = "SPECTATOR",
                            Name = "Spectator"
                        },
                        new
                        {
                            RoleId = 5,
                            Code = "ADMIN",
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentId"));

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasFilter("\"LicenseNumber\" IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@horserace.com",
                            FullName = "System Admin",
                            IsActive = true,
                            IsProfileComplete = false,
                            PasswordHash = "$2a$11$nBZal3z4rIa2vWJW427jmOF/ExTYwIZmKB6AZzcu4SlcKdv6MXyNq",
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Violation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ViolationId"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Penalty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportedByRefereeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ViolationId");

                    b.HasIndex("EntryId");

                    b.HasIndex("ReportedByRefereeId");

                    b.HasIndex("RaceId", "LegNumber");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.WalletTransaction", b =>
                {
                    b.Property<long>("WalletTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WalletTransactionId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("PerformedBy")
                        .HasColumnType("integer");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("WalletTransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_WalletTransactions_BalanceAfter", "\"BalanceAfter\" >= 0");
                        });
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Entry", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Entries_ApprovedBy");

                    b.HasOne("HorseRace.DAL.Entities.Horse", "Horse")
                        .WithMany("Entries")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRace.DAL.Entities.User", "HorseOwner")
                        .WithMany()
                        .HasForeignKey("HorseOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Entries_Owner");

                    b.HasOne("HorseRace.DAL.Entities.User", "Jockey")
                        .WithMany()
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Entries_Jockey");

                    b.HasOne("HorseRace.DAL.Entities.Race", "Race")
                        .WithMany("Entries")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("HorseOwner");

                    b.Navigation("Jockey");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Horse", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Horses_ApprovedBy");

                    b.HasOne("HorseRace.DAL.Entities.User", "Owner")
                        .WithMany("OwnedHorses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.JockeyInvitation", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.Horse", "Horse")
                        .WithMany("Invitations")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRace.DAL.Entities.User", "HorseOwner")
                        .WithMany("SentInvitations")
                        .HasForeignKey("HorseOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_JockeyInvitations_Owner");

                    b.HasOne("HorseRace.DAL.Entities.User", "Jockey")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_JockeyInvitations_Jockey");

                    b.HasOne("HorseRace.DAL.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("HorseOwner");

                    b.Navigation("Jockey");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Leg", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.Race", "Race")
                        .WithMany("Legs")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.LegOfficialResult", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.Entry", "Entry")
                        .WithMany("LegOfficialResults")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRace.DAL.Entities.Leg", "Leg")
                        .WithMany("OfficialResults")
                        .HasForeignKey("RaceId", "LegNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Leg");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.LegRefereeEntry", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.Entry", "Entry")
                        .WithMany("LegRefereeEntries")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRace.DAL.Entities.User", "Referee")
                        .WithMany()
                        .HasForeignKey("RefereeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LegRefereeEntries_Referee");

                    b.HasOne("HorseRace.DAL.Entities.Leg", "Leg")
                        .WithMany("RefereeEntries")
                        .HasForeignKey("RaceId", "LegNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Leg");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.PasswordResetOtp", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.PointWallet", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.User", "User")
                        .WithOne("PointWallet")
                        .HasForeignKey("HorseRace.DAL.Entities.PointWallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Prediction", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.Entry", "FirstEntry")
                        .WithMany()
                        .HasForeignKey("FirstEntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Predictions_Entry1");

                    b.HasOne("HorseRace.DAL.Entities.Race", "Race")
                        .WithMany("Predictions")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRace.DAL.Entities.Entry", "SecondEntry")
                        .WithMany()
                        .HasForeignKey("SecondEntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Predictions_Entry2");

                    b.HasOne("HorseRace.DAL.Entities.Entry", "ThirdEntry")
                        .WithMany()
                        .HasForeignKey("ThirdEntryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Predictions_Entry3");

                    b.HasOne("HorseRace.DAL.Entities.User", "User")
                        .WithMany("Predictions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstEntry");

                    b.Navigation("Race");

                    b.Navigation("SecondEntry");

                    b.Navigation("ThirdEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Race", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.User", "Referee1")
                        .WithMany()
                        .HasForeignKey("Referee1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Races_Referee1");

                    b.HasOne("HorseRace.DAL.Entities.User", "Referee2")
                        .WithMany()
                        .HasForeignKey("Referee2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Races_Referee2");

                    b.HasOne("HorseRace.DAL.Entities.Tournament", "Tournament")
                        .WithMany("Races")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referee1");

                    b.Navigation("Referee2");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.RaceResult", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.Entry", "Entry")
                        .WithOne("RaceResult")
                        .HasForeignKey("HorseRace.DAL.Entities.RaceResult", "EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRace.DAL.Entities.Race", "Race")
                        .WithMany("RaceResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.User", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Violation", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRace.DAL.Entities.User", "ReportedByReferee")
                        .WithMany()
                        .HasForeignKey("ReportedByRefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Violations_Referee");

                    b.HasOne("HorseRace.DAL.Entities.Leg", "Leg")
                        .WithMany("Violations")
                        .HasForeignKey("RaceId", "LegNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Leg");

                    b.Navigation("ReportedByReferee");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.WalletTransaction", b =>
                {
                    b.HasOne("HorseRace.DAL.Entities.PointWallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Entry", b =>
                {
                    b.Navigation("LegOfficialResults");

                    b.Navigation("LegRefereeEntries");

                    b.Navigation("RaceResult");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Horse", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Leg", b =>
                {
                    b.Navigation("OfficialResults");

                    b.Navigation("RefereeEntries");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.PointWallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Race", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Legs");

                    b.Navigation("Predictions");

                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.Tournament", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("HorseRace.DAL.Entities.User", b =>
                {
                    b.Navigation("OwnedHorses");

                    b.Navigation("PointWallet");

                    b.Navigation("Predictions");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentInvitations");
                });
#pragma warning restore 612, 618
        }
    }
}
