// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260624052923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.Entities.Entry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GateNumber")
                        .HasColumnType("integer");

                    b.Property<int>("HorseId")
                        .HasColumnType("integer");

                    b.Property<int>("HorseOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("JockeyId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EntryId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("HorseId");

                    b.HasIndex("HorseOwnerId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId", "GateNumber")
                        .IsUnique()
                        .HasFilter("\"GateNumber\" IS NOT NULL");

                    b.HasIndex("RaceId", "HorseId")
                        .IsUnique();

                    b.HasIndex("RaceId", "JockeyId")
                        .IsUnique();

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Horse", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HorseId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("Breed")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("HorseId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("OwnerId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.JockeyInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvitationId"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorseId")
                        .HasColumnType("integer");

                    b.Property<int>("HorseOwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("JockeyId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("InvitationId");

                    b.HasIndex("HorseId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId");

                    b.HasIndex("HorseOwnerId", "JockeyId", "HorseId", "RaceId")
                        .IsUnique();

                    b.ToTable("JockeyInvitations");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.JockeyProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("CareerPrizePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalRaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalTop3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("UserId");

                    b.ToTable("JockeyProfiles");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Leg", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<string>("AdminOverrideReason")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmationType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ConflictReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("RaceId", "LegNumber");

                    b.ToTable("Legs", t =>
                        {
                            t.HasCheckConstraint("CK_Legs_LegNumber", "\"LegNumber\" >= 1 AND \"LegNumber\" <= 10");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.LegOfficialResult", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfirmationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfirmedByAdminId")
                        .HasColumnType("integer");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("integer");

                    b.Property<int>("LegPoints")
                        .HasColumnType("integer");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("RaceId", "LegNumber", "EntryId");

                    b.HasIndex("EntryId");

                    b.ToTable("LegOfficialResults");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.LegRefereeEntry", b =>
                {
                    b.Property<long>("LegRefereeEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LegRefereeEntryId"));

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("integer");

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("RefereeUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LegRefereeEntryId");

                    b.HasIndex("EntryId");

                    b.HasIndex("RefereeUserId");

                    b.HasIndex("RaceId", "LegNumber", "EntryId", "RefereeUserId")
                        .IsUnique();

                    b.ToTable("LegRefereeEntries");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PasswordResetOtp", b =>
                {
                    b.Property<long>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OtpId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetOtps");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PointWallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(100m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFrozen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SpectatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WalletId");

                    b.HasIndex("SpectatorId")
                        .IsUnique();

                    b.ToTable("PointWallets", t =>
                        {
                            t.HasCheckConstraint("CK_PointWallets_Balance", "\"Balance\" >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Prediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PredictionId"));

                    b.Property<decimal>("BetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FirstEntryId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OddsLocked1")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("OddsLocked2")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<decimal>("OddsLocked3")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("SecondEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("SpectatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ThirdEntryId")
                        .HasColumnType("integer");

                    b.HasKey("PredictionId");

                    b.HasIndex("FirstEntryId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SecondEntryId");

                    b.HasIndex("SpectatorId");

                    b.HasIndex("Status");

                    b.HasIndex("ThirdEntryId");

                    b.HasIndex("RaceId", "SpectatorId", "Status");

                    b.ToTable("Predictions", t =>
                        {
                            t.HasCheckConstraint("CK_Predictions_BetAmount", "\"BetAmount\" >= 10");

                            t.HasCheckConstraint("CK_Predictions_DifferentEntries", "\"FirstEntryId\" <> \"SecondEntryId\" AND \"FirstEntryId\" <> \"ThirdEntryId\" AND \"SecondEntryId\" <> \"ThirdEntryId\"");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PredictionSettlement", b =>
                {
                    b.Property<int>("PredictionSettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PredictionSettlementId"));

                    b.Property<decimal>("BetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsRollbacked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OddsAverage")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("PayoutAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("PayoutTransactionId")
                        .HasColumnType("integer");

                    b.Property<int>("PredictionId")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RollbackAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RollbackOfSettlementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SettlementRunId")
                        .HasColumnType("integer");

                    b.Property<int>("SpectatorId")
                        .HasColumnType("integer");

                    b.HasKey("PredictionSettlementId");

                    b.HasIndex("Outcome");

                    b.HasIndex("PayoutTransactionId");

                    b.HasIndex("PredictionId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RollbackOfSettlementId");

                    b.HasIndex("SettlementRunId");

                    b.HasIndex("SpectatorId");

                    b.HasIndex("SettlementRunId", "PredictionId")
                        .IsUnique();

                    b.ToTable("PredictionSettlements", t =>
                        {
                            t.HasCheckConstraint("CK_PredictionSettlements_MatchedCount", "\"MatchedCount\" >= 0 AND \"MatchedCount\" <= 3");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PrizePointTransaction", b =>
                {
                    b.Property<int>("PrizePointTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PrizePointTransactionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<int>("FinalPosition")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int?>("RollbackOfId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PrizePointTransactionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntryId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RollbackOfId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId");

                    b.HasIndex("RaceId", "EntryId");

                    b.HasIndex("UserId", "TransactionType");

                    b.HasIndex("UserId", "TournamentId", "RaceId");

                    b.ToTable("PrizePointTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_PrizePointTransactions_FinalPosition", "\"FinalPosition\" >= 1");

                            t.HasCheckConstraint("CK_PrizePointTransactions_Points", "\"Points\" >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RaceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxHorses")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfLegs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OddsComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Referee1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Referee2Id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RegistrationCloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RegistrationOpenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RaceId");

                    b.HasIndex("Referee1Id");

                    b.HasIndex("Referee2Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Races", t =>
                        {
                            t.HasCheckConstraint("CK_Races_DifferentReferees", "\"Referee1Id\" <> \"Referee2Id\"");

                            t.HasCheckConstraint("CK_Races_NumberOfLegs", "\"NumberOfLegs\" >= 1 AND \"NumberOfLegs\" <= 10");
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.RaceResult", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinalPosition")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRaceDQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LegTop3Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("LegWinCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RaceId", "EntryId");

                    b.HasIndex("EntryId");

                    b.HasIndex("RaceId", "EntryId")
                        .IsUnique();

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Code = "HORSE_OWNER",
                            Name = "Horse Owner"
                        },
                        new
                        {
                            RoleId = 2,
                            Code = "JOCKEY",
                            Name = "Jockey"
                        },
                        new
                        {
                            RoleId = 3,
                            Code = "REFEREE",
                            Name = "Race Referee"
                        },
                        new
                        {
                            RoleId = 4,
                            Code = "SPECTATOR",
                            Name = "Spectator"
                        },
                        new
                        {
                            RoleId = 5,
                            Code = "ADMIN",
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.SettlementRun", b =>
                {
                    b.Property<int>("SettlementRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SettlementRunId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("TotalBetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalPayoutAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalPredictions")
                        .HasColumnType("integer");

                    b.Property<int?>("TriggeredByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("SettlementRunId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RaceId");

                    b.HasIndex("Status");

                    b.HasIndex("TriggeredByAdminId");

                    b.HasIndex("Type");

                    b.ToTable("SettlementRuns");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Spectator", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Spectators");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TournamentId"));

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfileComplete")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasFilter("\"LicenseNumber\" IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@horserace.com",
                            FullName = "System Admin",
                            IsActive = true,
                            IsProfileComplete = false,
                            PasswordHash = "$2a$11$cHcPtVLvCvKHR/30b2HuQOMs7GqrfTEAr5FcjLqCQzf9zCECIqqmW",
                            RoleId = 5,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Violation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ViolationId"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EntryId")
                        .HasColumnType("integer");

                    b.Property<int>("LegNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Penalty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportedByRefereeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ViolationId");

                    b.HasIndex("EntryId");

                    b.HasIndex("ReportedByRefereeId");

                    b.HasIndex("RaceId", "LegNumber");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.WalletTransaction", b =>
                {
                    b.Property<int>("WalletTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WalletTransactionId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PredictionId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("RollbackOfTransactionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SettlementRunId")
                        .HasColumnType("integer");

                    b.Property<int>("SpectatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("WalletTransactionId");

                    b.HasIndex("AdminId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PredictionId");

                    b.HasIndex("RollbackOfTransactionId");

                    b.HasIndex("SettlementRunId");

                    b.HasIndex("SpectatorId");

                    b.HasIndex("Type");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Entry", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Entries_ApprovedBy");

                    b.HasOne("Domain.Aggregates.Entities.Horse", "Horse")
                        .WithMany("Entries")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.User", "HorseOwner")
                        .WithMany()
                        .HasForeignKey("HorseOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Entries_Owner");

                    b.HasOne("Domain.Aggregates.Entities.User", "Jockey")
                        .WithMany()
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Entries_Jockey");

                    b.HasOne("Domain.Aggregates.Entities.Race", "Race")
                        .WithMany("Entries")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("HorseOwner");

                    b.Navigation("Jockey");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Horse", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Horses_ApprovedBy");

                    b.HasOne("Domain.Aggregates.Entities.User", "Owner")
                        .WithMany("OwnedHorses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.JockeyInvitation", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Horse", "Horse")
                        .WithMany("Invitations")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.User", "HorseOwner")
                        .WithMany("SentInvitations")
                        .HasForeignKey("HorseOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_JockeyInvitations_Owner");

                    b.HasOne("Domain.Aggregates.Entities.User", "Jockey")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_JockeyInvitations_Jockey");

                    b.HasOne("Domain.Aggregates.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("HorseOwner");

                    b.Navigation("Jockey");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.JockeyProfile", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.Aggregates.Entities.JockeyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Leg", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Race", "Race")
                        .WithMany("Legs")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.LegOfficialResult", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Entry", "Entry")
                        .WithMany("LegOfficialResults")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.Leg", "Leg")
                        .WithMany("OfficialResults")
                        .HasForeignKey("RaceId", "LegNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Leg");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.LegRefereeEntry", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Entry", "Entry")
                        .WithMany("LegRefereeEntries")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.User", "Referee")
                        .WithMany()
                        .HasForeignKey("RefereeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LegRefereeEntries_Referee");

                    b.HasOne("Domain.Aggregates.Entities.Leg", "Leg")
                        .WithMany("RefereeEntries")
                        .HasForeignKey("RaceId", "LegNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Leg");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PasswordResetOtp", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PointWallet", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Spectator", "Spectator")
                        .WithOne("PointWallet")
                        .HasForeignKey("Domain.Aggregates.Entities.PointWallet", "SpectatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Spectator");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Prediction", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Entry", "FirstEntry")
                        .WithMany()
                        .HasForeignKey("FirstEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Predictions_FirstEntry");

                    b.HasOne("Domain.Aggregates.Entities.Race", "Race")
                        .WithMany("Predictions")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.Entry", "SecondEntry")
                        .WithMany()
                        .HasForeignKey("SecondEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Predictions_SecondEntry");

                    b.HasOne("Domain.Aggregates.Entities.Spectator", "Spectator")
                        .WithMany("Predictions")
                        .HasForeignKey("SpectatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.Entry", "ThirdEntry")
                        .WithMany()
                        .HasForeignKey("ThirdEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Predictions_ThirdEntry");

                    b.Navigation("FirstEntry");

                    b.Navigation("Race");

                    b.Navigation("SecondEntry");

                    b.Navigation("Spectator");

                    b.Navigation("ThirdEntry");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PredictionSettlement", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.WalletTransaction", "PayoutTransaction")
                        .WithMany()
                        .HasForeignKey("PayoutTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PredictionSettlements_PayoutTransaction");

                    b.HasOne("Domain.Aggregates.Entities.Prediction", "Prediction")
                        .WithMany()
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.PredictionSettlement", "RollbackOfSettlement")
                        .WithMany("RollbackSettlements")
                        .HasForeignKey("RollbackOfSettlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PredictionSettlements_RollbackOfSettlement");

                    b.HasOne("Domain.Aggregates.Entities.SettlementRun", "SettlementRun")
                        .WithMany("PredictionSettlements")
                        .HasForeignKey("SettlementRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.Spectator", "Spectator")
                        .WithMany("PredictionSettlements")
                        .HasForeignKey("SpectatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PayoutTransaction");

                    b.Navigation("Prediction");

                    b.Navigation("Race");

                    b.Navigation("RollbackOfSettlement");

                    b.Navigation("SettlementRun");

                    b.Navigation("Spectator");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PrizePointTransaction", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.PrizePointTransaction", "RollbackOf")
                        .WithMany("Rollbacks")
                        .HasForeignKey("RollbackOfId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_PrizePointTransactions_RollbackOf");

                    b.HasOne("Domain.Aggregates.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.RaceResult", "RaceResult")
                        .WithMany("PrizePointTransactions")
                        .HasForeignKey("RaceId", "EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Race");

                    b.Navigation("RaceResult");

                    b.Navigation("RollbackOf");

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Race", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.User", "Referee1")
                        .WithMany()
                        .HasForeignKey("Referee1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Races_Referee1");

                    b.HasOne("Domain.Aggregates.Entities.User", "Referee2")
                        .WithMany()
                        .HasForeignKey("Referee2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_Races_Referee2");

                    b.HasOne("Domain.Aggregates.Entities.Tournament", "Tournament")
                        .WithMany("Races")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referee1");

                    b.Navigation("Referee2");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.RaceResult", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Entry", "Entry")
                        .WithMany("RaceResults")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.Race", "Race")
                        .WithMany("RaceResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.SettlementRun", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.User", "TriggeredByAdmin")
                        .WithMany()
                        .HasForeignKey("TriggeredByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SettlementRuns_TriggeredByAdmin");

                    b.Navigation("Race");

                    b.Navigation("TriggeredByAdmin");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Spectator", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Domain.Aggregates.Entities.Spectator", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.User", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Violation", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.Entry", "Entry")
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.User", "ReportedByReferee")
                        .WithMany()
                        .HasForeignKey("ReportedByRefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Violations_Referee");

                    b.HasOne("Domain.Aggregates.Entities.Leg", "Leg")
                        .WithMany("Violations")
                        .HasForeignKey("RaceId", "LegNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Leg");

                    b.Navigation("ReportedByReferee");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Domain.Aggregates.Entities.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_WalletTransactions_Admin");

                    b.HasOne("Domain.Aggregates.Entities.Prediction", "Prediction")
                        .WithMany()
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Aggregates.Entities.WalletTransaction", "RollbackOfTransaction")
                        .WithMany("RollbackTransactions")
                        .HasForeignKey("RollbackOfTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_WalletTransactions_RollbackOfTransaction");

                    b.HasOne("Domain.Aggregates.Entities.SettlementRun", "SettlementRun")
                        .WithMany()
                        .HasForeignKey("SettlementRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Aggregates.Entities.Spectator", "Spectator")
                        .WithMany()
                        .HasForeignKey("SpectatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.Entities.PointWallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Prediction");

                    b.Navigation("RollbackOfTransaction");

                    b.Navigation("SettlementRun");

                    b.Navigation("Spectator");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Entry", b =>
                {
                    b.Navigation("LegOfficialResults");

                    b.Navigation("LegRefereeEntries");

                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Horse", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Leg", b =>
                {
                    b.Navigation("OfficialResults");

                    b.Navigation("RefereeEntries");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PointWallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PredictionSettlement", b =>
                {
                    b.Navigation("RollbackSettlements");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.PrizePointTransaction", b =>
                {
                    b.Navigation("Rollbacks");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Race", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Legs");

                    b.Navigation("Predictions");

                    b.Navigation("RaceResults");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.RaceResult", b =>
                {
                    b.Navigation("PrizePointTransactions");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.SettlementRun", b =>
                {
                    b.Navigation("PredictionSettlements");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Spectator", b =>
                {
                    b.Navigation("PointWallet");

                    b.Navigation("PredictionSettlements");

                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.Tournament", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.User", b =>
                {
                    b.Navigation("OwnedHorses");

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentInvitations");
                });

            modelBuilder.Entity("Domain.Aggregates.Entities.WalletTransaction", b =>
                {
                    b.Navigation("RollbackTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
